CREATE TABLE COMMITS (
  COMMIT_SHA VARCHAR(500),
  COMMIT_URL VARCHAR(5000),
  COMMIT_MESSAGE VARCHAR(5000),
  COMMIT_DATE DATE,
  AUTHOR_ID INTEGER,
  LOGIN_NAME VARCHAR(50),
  CREATION_DATE DATE
);

CREATE UNIQUE INDEX commit_index ON commits (COMMIT_URL);

CREATE TABLE AUTHOR (
  ID SERIAL,
  LOGIN_NAME VARCHAR(50),
  EMAIL VARCHAR(150),
  EMAIL_COMPANY VARCHAR(150),
  CREATION_DATE DATE
);

CREATE UNIQUE INDEX author_index ON AUTHOR (LOGIN_NAME);